### ISSUE TITLE
Dynmap plot highlights do not match real plot borders

### ISSUE THREAD

**Issue by EvilOlaf** [WorldCretornica/Dynmap-PlotMe#2]
Link to snapped screenshot: http://www0.xup.to/exec/ximg.php?fid=19417770
Another picture: http://www0.xup.to/exec/ximg.php?fid=20045142
You can see that the line which defines the plot borders does not match the real plot borders. One block of the street  at the left and at the top side do not belong to the plot.

dynmap-plotme config

```
# dynmap-plotme configuration
update:
  period: 300
  onchange: true
layer:
  name: City
  hidebydefault: false
  layerprio: 1
  minzoom: 0
resdepth: 2
infowindow: '<div class="infowindow"><span style="font-size:120%;">ID : %plotid%</span><br
  /> Besitzer <span style="font-weight:bold;">%plotowners%</span>%plothelpers%'
plotstyle:
  strokeColor: '#FF0000'
  strokeOpacity: 0.5
  strokeWeight: 1
  fillColor: '#FFFFFF'
  fillOpacity: 0.05
visibleregions: []
hiddenregions: []
custstyle:
  customizedplot:
    strokeColor: '#00FF00'
    y: 64
  anotherregion:
    subzone:
      strokeColor: '#007F00'
```

plotme-defaultgenerator config

```
worlds:
  city:
    PlotFloorBlock: '2'
    XTranslation: 0
    RoadAltBlock: '13'
    RoadMainBlock: '43'
    GroundHeight: 60
    FillBlock: '3'
    ZTranslation: 0
    WallBlock: '44:5'
    PathWidth: 7
    ForSaleWallBlock: '44:1'
    ProtectedWallBlock: '44:4'
    AuctionWallBlock: '44:1'
    PlotSize: 51
```

I did not post the config of plotme itself, because I tought there is nothing interesting to this case inside.

Running PlotMe 0.15.1 @ git-Spigot-f234263-2db3ea2
